# Generated by Django 2.2.12 on 2021-11-01 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20211101_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], default='M', max_length=6),
        ),
    ]
